// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfgcf3t3zEEyJnzUuIYiiyns1pMAJC4XQ',
    appId: '1:182067948842:web:4b390cade698301f854253',
    messagingSenderId: '182067948842',
    projectId: 'fish-radar-feedback',
    authDomain: 'fish-radar-feedback.firebaseapp.com',
    storageBucket: 'fish-radar-feedback.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGt5izSvFm5ChTmeTnTzLTjmLMTLcJeY0',
    appId: '1:182067948842:android:90f75a28582b47d4854253',
    messagingSenderId: '182067948842',
    projectId: 'fish-radar-feedback',
    storageBucket: 'fish-radar-feedback.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgChrvByT4vj9wCFUClkKJ1cCgZj-2uhE',
    appId: '1:182067948842:ios:600062d4a3deeeb5854253',
    messagingSenderId: '182067948842',
    projectId: 'fish-radar-feedback',
    storageBucket: 'fish-radar-feedback.appspot.com',
    iosBundleId: 'com.example.fishRadarSc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgChrvByT4vj9wCFUClkKJ1cCgZj-2uhE',
    appId: '1:182067948842:ios:ad35013dd5a92dab854253',
    messagingSenderId: '182067948842',
    projectId: 'fish-radar-feedback',
    storageBucket: 'fish-radar-feedback.appspot.com',
    iosBundleId: 'com.example.fishRadarSc.RunnerTests',
  );
}
